### ISSUE TITLE
Can't delete or update.

### ISSUE THREAD

**Issue by Tina03031** [faridsabitov/Sketch-Connection-Flow-Arrows#19]
I just installed the plugin. I can create connections, but not delete or update them. I get a message that says there is no connection between the selected layers. I know there is a connection. The artboard contains only the two node layers plus the arrow. 

Also, the hotkey for creating a connection doesn't work. I can only create using the menu.

I had high hopes for using this plugin, but so far, no luck.
<img width="1280" alt="connectionsPlugin" src="https://user-images.githubusercontent.com/53238863/61749569-0e0aa880-ad71-11e9-8fe5-3bc954794cf6.png">

**Comment by faridsabitov** [comment]
Hi @Tina03031!

I've uploaded a new update, please check it out! There is an auto-update feature!

All the best,
Farid
