### ISSUE TITLE
Arrow connections not surviving document close - reopen

### ISSUE THREAD

**Issue by ztotik** [faridsabitov/Sketch-Connection-Flow-Arrows#21]
In Sketch 61 arrow connections added with the plugin vanish after moving either layer they were connecting. The end result is that arrows do not survive a document close-open in an editable way.

**Comment by ztotik** [comment]
Experimented some more:
- the problem only appears when using the custom styling feature:
- if I name my custom arrow style to $arrow it works fine - if I name it to $arrow-something, then the error occurs

**Comment by faridsabitov** [comment]
Thank you @xzenx! Will take a look and will try to provide a new update!

All the best,
Farid

**Comment by faridsabitov** [comment]
Hi @xzenx, 

I tried to reproduce it and I couldn't. If you still facing this problem we can have a quick call via http://callendly.com/faridsabitov and will try to help!

Thank you!
