### ISSUE TITLE
Does not work on Version 61.2

### ISSUE THREAD

**Issue by eledeth** [faridsabitov/Sketch-Connection-Flow-Arrows#22]
I just downloaded the plugin, but it doesn't connect at all. Arrows are not appearing.
My sketch Version is 61.2

**Comment by romainehinds17** [comment]
I just ran into this myself. I solved it by creating a large blank artboard and overlaying my other artboards on top.

**Comment by eledeth** [comment]
I tried but it doesn't work either.
I have copied all artboards and layers to a new document and it works. :)

**Comment by faridsabitov** [comment]
Hello all, I just came back from the holidays and will update everything :)

If you would like to have a quick call and share all your feedback, here is my available time: https://calendly.com/faridsabitov

**Comment by faridsabitov** [comment]
Hello all, I couldn't replicate the problem and looks like everything is works fine. Please contact me if you still facing this problem via https://calendly.com/faridsabitov 

Thank you!
