### ISSUE TITLE
Arrows not exporting with PDF

### ISSUE THREAD

**Issue by mrengy** [faridsabitov/Sketch-Connection-Flow-Arrows#23]
I created a bunch of arrows in Sketch, and I exported my artboards to PDF using "File" > "Export Artboards to PDF". The PDF contains other objects but not any of the connection arrows. I also tried printing as a PDF but had the same result. How can I include the arrows in the exported PDF? 
See page 2 [QIP Navigation (QIP Navigation).pdf](https://github.com/faridsabitov/Sketch-Connection-Flow-Arrows/files/4330064/QIP.Navigation.QIP.Navigation.pdf)

Mac OS 10.14.6 (18G3020)
Sketch Version 63.1 (92452)
Plugin version 3.0.1

**Comment by faridsabitov** [comment]
Hi Mike,

Please make sure that the arrows folder is inside the artboard that you exporting. You can try using slice tool in Sketch.

Hope that will help,
Farid

**Comment by mrengy** [comment]
Moving the arrows folder inside the artboard resolved it. Thank you!
